export const dataSource = [
    {
        key: "lesson1",
        lessonNumber: 1,
        monday: "",
        tuesday: "Математика",
        wednesday: "Укр. мова",
        thursday: "",
        friday: "",
        saturday: "",
        sunday: "",
    },
    {
        key: "lesson2",
        lessonNumber: 2,
        monday: "Фізична культура",
        tuesday: "Програмування",
        wednesday: "",
        thursday: "",
        friday: "Проектування",
        saturday: "",
        sunday: "",
    },
    {
        key: "lesson3",
        lessonNumber: 3,
        monday: "",
        tuesday: "",
        wednesday: "",
        thursday: "",
        friday: "Англійська мова",
        saturday: "",
        sunday: "",
    },
    {
        key: "lesson4",
        lessonNumber: 4,
        monday: "",
        tuesday: "Математика",
        wednesday: "Укр. мова",
        thursday: "",
        friday: "",
        saturday: "",
        sunday: "",
    },
    {
        key: "lesson5",
        lessonNumber: 5,
        monday: "",
        tuesday: "Математика",
        wednesday: "Укр. мова",
        thursday: "",
        friday: "",
        saturday: "",
        sunday: "",
    },
];

export const columns = [
    {
        title: "№ пари",
        dataIndex: "lessonNumber",
        key: "lessonNumber",
    },
    {
        title: "Понеділок",
        dataIndex: "monday",
        key: "monday",
    },
    {
        title: "Вівторок",
        dataIndex: "tuesday",
        key: "tuesday",
        style: { backgroundColor: "blue" },
        className: "currentDate",
    },
    {
        title: "Середа",
        dataIndex: "wednesday",
        key: "wednesday",
    },
    {
        title: "Четвер",
        dataIndex: "thursday",
        key: "thursday",
    },
    {
        title: "П'ятниця",
        dataIndex: "friday",
        key: "friday",
    },
    {
        title: "Субота",
        dataIndex: "saturday",
        key: "saturday",
    },
    {
        title: "Неділя",
        dataIndex: "sunday",
        key: "sunday",
    },
];